Initial code
eclipse/microprofile-service-mesh-service-b pull request #2
Opened 2018-06-19 14:56 UTC by jonhawkes

Signed-off-by: Jon Hawkes <jon.hawkes@uk.ibm.com>

2018-06-19 15:03 UTC, kenfinnigan commented
I think it's best if all the Liberty specific pieces are in their own profile.

In addition, it shouldn't have a parent POM that's Liberty specific.

2018-06-19 15:30 UTC, Emily-Jiang requested changes

2018-06-19 15:30 UTC, Emily-Jiang commented on src/main/java/application/rest/HealthEndpoint.java
> +package application.rest;
please add copyright for service-a and service-b.

2018-06-19 16:25 UTC, kenfinnigan commented on src/main/java/application/rest/HealthEndpoint.java
> +public class HealthEndpoint implements HealthCheck, ServletContextListener {
Not sure we should be using Servlet spec bits in MP, as it's technically not needed for MP. Not all implementations will be based on Servlet

2018-06-26 10:33 UTC, jonhawkes commented
Fixes https://github.com/eclipse/microprofile-service-mesh-service-a/issues/3 but for service-b!

2018-07-11 12:58 UTC, closed without merging